package com.coalmine.jstately.test;

public enum EventType {
	STATE_ENTERED,
	STATE_EXITED,
	COMPOSITE_STATE_ENTERED,
	COMPOSITE_STATE_EXITED,
	TRANSITION_FOLLOWED,
	NO_VALID_TRANSITION_FOUND
}


